name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++

      - name: Compile and run tests
        working-directory: motors
        run: |
          g++ MotorControlTest.cpp -o MotorControlTest
          ./MotorControlTest
